name: Build Wolfi Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Melange
        uses: chainguard-dev/actions/setup-melange@main

      - name: Build Melange Package
        run: |
          melange keygen melange.rsa
          sudo melange build fnirsi-dps-150.yaml \
            --arch x86_64,aarch64 \
            --signing-key melange.rsa

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: chainguard-images/actions/apko-publish@main
        with:
          config: apko.yaml
          tag: ghcr.io/${{ github.repository_owner }}/fnirsi-dps-150:latest
          keyring-append: melange.rsa.pub
          archs: x86_64,aarch64
